### PR TITLE
feat(website): establish site infrastructure and layout

### PR DESCRIPTION
**Pull request by duanwilliam**
~~duplicate of #5 , should hopefully have pr deploy previews now~~

Fleshes out the basic framework/infrastructure for the website. Specifically, this PR currently...
- [x] creates directory index pages, where each directory index displays a grid of its immediate children.
- [x] gather file and folder titles and descriptions
    - for folders: the title is the directory name (if it's a directory), the description the number of **direct** children (i.e. it does not count the number of workshops (leaves) inside. that may be a better idea, but i don't think it's possible with my current algorithm)
    - for files: the title is the leading H1 heading of the notebook file, and the description the line directly following it. Basically, start each notebook with a Markdown cell with an H1 heading of the workshop title, and optionally text following that is the description. The title and description can both contain any Markdown styling (e.g. **bold**, _italic_, ~~strikethrough~~, `inline code`, and LaTeX)
- [x] renders a navbar
- [x] builds a sidebar of the full workshops directory structure. The path along the sidebar tree to the current page is highlighted.
    - the sidebar uses the aforementioned titles gathered. yes, it will render Markdown styling.
- [x] table of contents (toc) to the side of each notebook
    - each heading now gets its own id which can be linked to. hovering over a heading reveals a direct link to that heading
    - yes, the toc items will render markdown styling
- [ ] displays output cells from jupyter notebooks
- [ ] mobile layout
- [ ] properly documents how every part works

the infrastructure is designed such that the sidebar and file structure tree generation is decoupled from specifically being about Jupyter notebooks or in the Workshops repo, and setting up a pipeline for e.g. converting Markdown or Python files in some folder should be as simple as adding a configuration to `src/lib/pipelines`

### CODE REVIEW

**Comment by duanwilliam** [comment]
o do not know why latest two commits broke build, will investigate later

**Comment by duanwilliam** [comment]
getting error on esbuild but cannot replicate it locally - will investigate later

**Comment by duanwilliam** [comment]
@StormFireFox1 i believe the netlify configuration is adding `target: serverless` to the Next config; this field appears to be deprecated on newer versions of Next: I got this output when trying to build with that field manually set.
```bash
~$ yarn build
yarn run v1.22.18
$ next build
warn  - The `target` config is deprecated and will be removed in a future version.
See more info here https://nextjs.org/docs/messages/deprecated-target-config
```

Could this be removed from the config?

**Comment by StormFireFox1** [comment]
Looked into it; Next.js in Netlify does not work with versions >=11 or so. Moved deployment to Vercel, you can excuse this PR's checks for a while.

**Review by StoneT2000 — APPROVED** [review]

**Pull request merged**
