### PR TITLE
Support rendering readmes and obtaining information from metadata file

### LINKED ISSUE #22: [website] proposal: support custom metadata file for setting category/notebook title, description, etc
could use format `[notebook name].metadata.yml` or something.
categories might just use a reserved name (to avoid naming collisions w/ its files), e.g. `__category.metadata.yml` or something.

### PR DESCRIPTION
**Pull request by duanwilliam**
closes #22

This PR introduces way too many features crammed into way too few commits.

- directories can now be associated with a file to render, and now only fall back to the grid of its children if no such file is present. by default, this means searching for `README.md`, `README`, and `README.txt` (all case-sensitive), in that order of precedence. 
- instead of having to rely on file/directory name and/or Markdown contents, we can now define metadata to associate with a file.
    - part of this means introducing a new file type/format, the `.acm-ai-metadata.yml` file type. This is YAML file with two fields: `title` and `description`. If no title is found, the metadata file will be treated as invalid and another method will be attempted.
    - for files, by default, this means searching for a file `[filename].acm-ai-metadata.yml`. If none is found, it falls back to searching for it in YAML frontmatter in the Markdown file contents. If none is found there, it falls back to trying to grab the first H1 heading of the file as the title, and the first paragraph after that heading as the description (this is similar, but slightly different, from prior behavior). If that fails as well, the title falls back to the file name with file extension removed, and the description falls back to an empty string
    - for directories, it depends on whether the directory has an associated file with it (see first bullet in this PR comment):
        - if the directory has no associated file, it will search for a file `[directory]/.acm-ai-metadata.yml`. If none is found, the title will fall back to the directory name, and the description to the number of "leaves" (i.e. workshops, possibly nested) within the directory (this is the previous behavior).
        - if the directory has an associated file, it will search for a file `[directory]/.acm-ai-metadata.yml`. If none is found, it falls back to searching for it in YAML frontmatter in the associated file's contents, or otherwise the first H1 heading and the first paragraph after it. If still not found, the title falls back to the directory name, and the description the number of leaves
    - tl;dr:
        - files (notebooks): `[filename].acm-ai-metadata.yml` -> file YAML frontmatter -> file structure -> fallback (filename)
        - directories, no readme: `[directory]/.acm-ai-metadata.yml` -> fallback (dirname & num leaves)
        - directories, with readme: `[directory]/.acm-ai-metdata.yml` -> readme YAML frontmatter -> readme file structure -> fallback (dirname & num leaves)
- to accompany all these changes, the pipeline has been significantly refactored to allow for flexibility in all these. The way files associated with a directory are resolved, how to coerce files into Markdown (e.g. the notebooks, or the files associated with a directory), how to extract the title and description from files, etc all can be customized in a config.
- current Markdown parser is somewhat unstable and hacky. it's now significantly refactored (again lol) to try to make it more robust. Specifically, it now handles nested HTML in Markdown much better, as well as HTML comments. It does still have some wonky behavior in certain cases though, I'm not sure if they've all been addressed so we still may end up with obscure bugs later down the line
    - it also is able to process the GitHub themed image syntax (`alt` / `alt` that we are using in the READMEs

### CODE REVIEW

**Comment by duanwilliam** [comment]
@arth-shukla i'd edited some of the readmes and notebooks locally when working on it for testing and to get it working. i also added YAML frontmatter to the readmes as testing so they display nicely on the website. i may have left some vestigial text / accidentally deleted something important though, feel free to fix those parts if you find any

**Comment by arth-shukla** [comment]
This looks amazing! It's so much better than anything I could've imagined. I think this is good to merge as-is for now (just to get all the README updates into `main`). I only have a few notes for some things for a future PR:

**On my end:**
1. I will update our new ACM Workshop Repo Templates to _always_ include the `title` and `description` frontmatter. Hopefully this will prevent any issues with the YAML frontmatter stuff, as anyone who uploads a workshop will likely fill those out (and hopefully not delete it)
2. I'll work with Jason to upload his adversarial workshop stuff, which should give a real-world test for us to see if there are any issues with event leads implementing all relevant info.

**Some comments:**
1. We have a set of templates under `Internal` in the ACM AI Workshops GitHub. If this hasn't been implemented already, can we make the ACM AI Wiki blind to this?
2. The NLP Series has resources other than the README and the Colab Notebooks. For example, we have presentations and summary graphics. It would be great to be able to access these in the ACM Wiki. Currently, all READMEs for individual workshops have local path links to all relevant resources (not everything, e.g. not the figures, but just the important resources). For an example, see section 3 here https://acm-ai-workshops-9fxv39rx5-acmucsd.vercel.app/workshops/sp22/nlp-series/workshop-1. Is there a way to detect these local paths and make the links work such that either a) they're rendered directly in the ACM Wiki, or b) they link to the file on GitHub so they can be automatically rendered there? (b) seems like the most straightforward option (path.join with GitHub link?), but I'm sure there's more complications for implementation.

Thanks again for getting this working. It looks gorgeous!

**Comment by duanwilliam** [comment]
linking if present in the wiki (e.g. the Main Notebook link) may be hard, making _all_ links go to the GitHub instead should be fairly simple though

**Review by StoneT2000 — APPROVED** [review]

**Comment by arth-shukla** [comment]
Ope sorry I added some stuff to that original message. Mainly just asking if you can make the Wiki blind to the `Internal` folder.

As for the links, some links go to external websites (e.g. LinkedIn, external resources, citations, etc). Can we have only the local paths (basically any link without http or https) go to GitHub?

**Review by arth-shukla — APPROVED** [review]

**Comment by duanwilliam** [comment]
@arth-shukla README relative links now redirect to GitHub instead, could you test and see if it's what you wanted?

**Comment by arth-shukla** [comment]
@duanwilliam currently getting an internal server error whenever i click on any of the sections

https://user-images.githubusercontent.com/44527268/170596969-748bfe58-9b33-41b9-a247-4ace17866c85.mov

**Comment by duanwilliam** [comment]
ok fixed, honestly still not sure why it happened since it worked locally and it said the build succeeded but i had a guess as to why and its working now in any case lol

**Comment by arth-shukla** [comment]
Yup, it all works on my end now. Looks good to go!

**Review by arth-shukla — APPROVED** [review]

**Pull request merged**
